### ISSUE TITLE
Common too big?

### ISSUE THREAD

**Issue by chrisflatley** [annot8/annot8-common#5]
I think common might be two repos:

* One for implementors of annot8 core (eg containing AbstractAnnotation, etc)
* One for common stuff like Text / Bounds which needs to be available to processor developers

The latter stuff could get moved straight away to conventions (though that's a slight bending on the original use of conventions)

**Comment by jamesdbaker** [comment]
What would be the name of the first repo? Would it fit into any of the others, or does it need it's own one? (Just conscious of creating lots of repos and having versioning issues between them)

Not sure about moving stuff to conventions.

**Comment by chrisflatley** [comment]
Alternative would be to move the implementors stuff.

That would naturally fit into default-impl, since that is all just helpers for implementation really.

Then some of the components stuff (eg base.*) could move into common.

**Comment by jamesdbaker** [comment]
I was thinking we might need a separate project (not necessarily repo) for the base component stuff if we're splitting the components out - might be better to move it into common if it's genuinely common stuff.

Is any of the implementors stuff a dependency of anything apart from the default-impl at the moment? (i.e. we don't want to end up in a situation where someone produces a different implementation but has to include default-impl anyway because it contains required classes).

**Comment by chrisflatley** [comment]
You are right, we don't need more repos. 

we can have this common repo which has multiple projects (which probably need better names that in this):
* common (parent project), having submodules:
* common-data (the .bounds and  .content form existing common repo)
* common-components (stuff you are talking about)
* common-implementation (rest of stuff form common) 

Don't know these should be prefixed common / support / lib

**Comment by chrisflatley** [comment]
Done
